export const navigationGroups = [
  { label: '', items: ['hub'] },
  { label: 'WORK', items: ['chat', 'memory', 'skills', 'files'] },
  { label: 'RUN', items: ['agents', 'tasks', 'channels', 'mcp', 'logs'] },
  { label: 'WATCH', items: ['activity', 'sessions', 'approvals'] },
  { label: 'TUNE', items: ['self-improve', 'analytics', 'docs', 'settings'] },
  {
    label: 'UI STATES',
    items: ['agent-detail', 'command-palette', 'approval-modal', 'trace-detail', 'new-task', 'notifications', 'release-log'],
  },
  {
    label: 'MOCKUP VARIANTS',
    items: ['cron', 'commitments', 'mobile-hub', 'mobile-chat', 'mobile-nav'],
  },
];

const page = (config) => ({
  kind: 'page',
  metrics: [],
  tabs: [],
  rows: [],
  details: [],
  api: [],
  relations: [],
  rowTargets: [],
  tabTargets: {},
  tabSections: {},
  defaultTab: null,
  primaryTarget: null,
  statusLabel: 'Healthy',
  presentation: 'desktop',
  ...config,
});

export const screens = {
  hub: page({
    title: 'Hub',
    navLabel: 'Hub',
    route: '/',
    subtitle: 'A complete view of HiveOS right now',
    action: 'New task',
    metrics: [
      ['Gateway', 'Healthy', 'Last heartbeat 14s ago'],
      ['Active agents', '3', '2 tasks running'],
      ['Memory', '12.4k', '98.7% index health'],
      ['Approvals', '1', 'Oldest waiting 8m'],
    ],
    section: 'Needs attention',
    rows: [
      ['Deploy production update', 'Approval', 'Waiting for operator review', 'Review'],
      ['Memory consolidation retry', 'Task', 'Ready to run safely', 'Inspect'],
      ['Daily model budget', 'Usage', '78% of daily limit', 'Open analytics'],
    ],
    detailsTitle: 'Active now',
    details: ['Gateway retry refactor', 'MCP compatibility research', 'Memory consolidation'],
    api: ['/health/summary', '/agents/board', '/memory/stats', '/approvals'],
    relations: ['/tasks', '/chat', '/activity', '/sessions'],
    rowTargets: ['approval-modal', 'tasks', 'analytics'],
    primaryTarget: 'new-task',
  }),
  chat: page({
    title: 'Chat',
    navLabel: 'Chat',
    route: '/chat/:sessionId?',
    subtitle: 'Work with Hive and review its execution',
    action: 'New chat',
    tabs: ['Conversation', 'Run details'],
    section: 'HiveOS UI architecture review',
    rows: [
      ['Hive', 'I reviewed the gateway contracts and mapped every UI dependency. The self-mod safety checks are wired correctly across all outcome paths.', 'Now', ''],
      ['Tool call', 'inspect_api_routes · 184 ms', 'Success', 'Open trace'],
      ['Delegation', 'reviewer is validating the contract matrix for all 17 canonical pages', 'Running', 'View agent'],
    ],
    detailsTitle: 'Run context',
    details: ['Session ses_8f912a', 'Model MiniMax M2.7', 'Memory 7 facts', 'Skills 3 loaded'],
    api: ['/chat/stream/iterations', '/sessions', '/memory/topics', '/skills'],
    relations: ['/sessions/:id', '/memory', '/skills', '/traces/:id'],
    rowTargets: [null, 'trace-detail', 'agent-detail'],
  }),
  memory: page({
    title: 'Memory',
    navLabel: 'Memory',
    route: '/memory',
    subtitle: 'Knowledge retained across agents',
    action: 'Add memory',
    metrics: [
      ['Memories', '12.4k', 'Across 8 namespaces'],
      ['Index health', '98.7%', 'Healthy'],
    ],
    tabs: ['All', 'Important', 'Topics', 'Sessions'],
    section: 'Recent memories',
    rows: [
      ['Release workflow preferences', 'Core platform', 'High', '2m ago'],
      ['Webhook retry failure analysis', 'Core platform', 'High', '12m ago'],
      ['Rate limit handling strategy', 'Operations', 'Medium', '45m ago'],
      ['Customer onboarding flow steps', 'Customer success', 'Medium', '1h ago'],
      ['Preferred communication style', 'Personal', 'Medium', '2h ago'],
    ],
    detailsTitle: 'Memory details',
    details: ['Type · Preference', 'Importance · High', 'Namespace · Core platform', 'Retention · Durable'],
    api: ['/memory/stats', '/memory/important', '/memory/topics', '/memory/session/{id}/count'],
    relations: ['/chat/:sessionId', '/docs/MNEMOSYNE.md', '/activity?tab=traces'],
  }),
  skills: page({
    title: 'Skills',
    navLabel: 'Skills',
    route: '/skills',
    subtitle: 'Reusable capabilities available to Hive',
    action: 'Add capability',
    tabs: ['Pinned', 'Active', 'Stale', 'Archived', 'All'],
    section: 'Skill library',
    rows: [
      ['system-health', 'Operational diagnostics and health checks', 'Pinned', 'Open'],
      ['memory-recovery', 'Mnemosyne recovery workflow', 'Active', 'Open'],
      ['github-pr-review', 'Review pull request changes end-to-end', 'Active', 'Open'],
      ['deployment-check', 'Pre-deploy validation and safety checks', 'Stale', 'Open'],
    ],
    detailsTitle: 'Lifecycle',
    details: ['Pinned skills 8', 'Active skills 24', 'Learned skills 3', 'Archived skills 5'],
    api: ['/skills', '/skills/{name}', '/skills/{name}/pin', '/skills/{name}/state'],
    relations: ['/chat', '/agents/:id', '/analytics?view=skills'],
  }),
  files: page({
    title: 'Files',
    navLabel: 'Files',
    route: '/files',
    subtitle: 'Browse and inspect the HiveOS workspace',
    action: 'Upload',
    tabs: ['Workspace', 'Recent', 'Shared'],
    section: 'Workspace',
    rows: [
      ['Config', 'Folder', '8 items', 'Open'],
      ['docs', 'Folder', '42 items', 'Open'],
      ['dashboard', 'Folder', '18 items', 'Open'],
      ['README.md', 'Markdown', '6 KB', 'Preview'],
    ],
    detailsTitle: 'Preview',
    details: ['README.md', 'Modified today', 'Markdown document', 'HiveOS project overview'],
    api: ['GAP: /files/tree', 'GAP: /files/content', 'GAP: /files/upload'],
    relations: ['/chat (attachment picker)', '/docs', '/settings?tab=personal'],
  }),
  agents: page({
    title: 'Agents',
    navLabel: 'Agents',
    route: '/agents',
    subtitle: 'Specialists working for Hive',
    tabs: ['Active now', 'All agents', 'By type'],
    section: 'Active agents',
    rows: [
      ['coder', 'Gateway retry refactor', 'Running', 'Open'],
      ['researcher', 'MCP compatibility audit', 'Running', 'Open'],
      ['memory-keeper', 'Consolidating facts', 'Running', 'Open'],
      ['reviewer', 'UI contract validation', 'Idle', 'Open'],
    ],
    detailsTitle: 'System summary',
    details: ['5 named specialists', '3 running', '1 idle', '1 on demand'],
    api: ['/agents/board', 'WS A2A_CALL_*', 'GAP: /agents/{id}/control'],
    relations: ['/agents/:agentId', '/tasks', '/activity'],
    rowTargets: ['agent-detail', 'agent-detail', 'agent-detail', 'agent-detail'],
  }),
  tasks: page({
    title: 'Tasks',
    navLabel: 'Tasks',
    route: '/tasks',
    subtitle: 'Queued, scheduled and recurring work',
    action: 'New task',
    tabs: ['Kanban', 'Cron', 'Promises'],
    section: 'Work queue',
    rows: [
      ['Refactor retry handling', 'In progress', 'coder', 'Inspect'],
      ['Review UI contract', 'Review', 'reviewer', 'Inspect'],
      ['Consolidate memory', 'Running', 'memory-keeper', 'Inspect'],
      ['MCP server audit', 'Backlog', 'researcher', 'Inspect'],
    ],
    detailsTitle: 'Queue health',
    details: ['12 pending', '3 running', '1 failed', 'Oldest pending 18m'],
    api: ['/tasks', '/tasks/by-kind', '/cron', '/commitments'],
    relations: ['/agents/:id', '/activity', '/approvals'],
    tabTargets: { Cron: 'cron', Promises: 'commitments' },
    primaryTarget: 'new-task',
  }),
  channels: page({
    title: 'Channels',
    navLabel: 'Channels',
    route: '/channels/:platform?',
    subtitle: 'Communication surfaces connected to Hive',
    tabs: ['Telegram', 'Discord', 'Slack', 'Email', 'Webhooks'],
    section: 'Connections',
    rows: [
      ['Telegram', 'Connected', 'Last message 4m ago', 'Manage'],
      ['Discord', 'Connected', 'Last message 18m ago', 'Manage'],
      ['Slack', 'Not configured', 'No credentials', 'Configure'],
      ['Email', 'Connected', 'Last message 1h ago', 'Manage'],
    ],
    detailsTitle: 'Selected channel',
    details: ['Status · Connected', 'Inbound · Healthy', 'Outbound · Healthy', 'Mapping · 3 chats'],
    api: ['/health/summary.channels', 'PARTIAL: channel webhooks', 'GAP: /channels management'],
    relations: ['/settings?tab=system', '/activity?tab=events', '/notifications'],
  }),
  mcp: page({
    title: 'MCP',
    navLabel: 'MCP',
    route: '/mcp',
    subtitle: 'External tools and context servers',
    action: 'Add server',
    tabs: ['Servers', 'Tools', 'Health'],
    section: 'MCP servers',
    rows: [
      ['Mnemosyne', 'Connected', '12 tools', 'Open'],
      ['GitHub', 'Connected', '18 tools', 'Open'],
      ['Filesystem', 'Connected', '7 tools', 'Open'],
      ['Browser', 'Degraded', '4 tools', 'Inspect'],
    ],
    detailsTitle: 'Server health',
    details: ['3 healthy', '1 degraded', '41 tools', 'Median latency 86 ms'],
    api: ['/tools', '/tools/stats', 'GAP: /mcp/servers CRUD', 'GAP: /mcp/health'],
    relations: ['/skills', '/settings?tab=account', '/activity'],
  }),
  logs: page({
    title: 'Logs',
    navLabel: 'Logs',
    route: '/logs',
    subtitle: 'Runtime output from HiveOS services',
    tabs: ['Gateway', 'Agents', 'System', 'Self-improve'],
    section: 'Live tail',
    rows: [
      ['03:42:18', 'INFO', 'gateway', 'Request completed in 184 ms'],
      ['03:42:16', 'INFO', 'memory', 'Consolidation checkpoint stored'],
      ['03:42:11', 'WARN', 'mcp', 'Browser server latency above threshold'],
      ['03:41:57', 'INFO', 'agent.coder', 'Task step 4 of 7 complete'],
    ],
    detailsTitle: 'Stream',
    details: ['Auto-scroll on', 'Source gateway', 'Level INFO+', 'Connected'],
    api: ['PARTIAL: /audit', 'WS /ws/dashboard', 'GAP: /logs/stream', 'GAP: /logs/export'],
    relations: ['/activity', '/traces/:id', '/settings?tab=system'],
  }),
  activity: page({
    title: 'Activity',
    navLabel: 'Activity',
    route: '/activity',
    subtitle: 'Live business events across HiveOS',
    tabs: ['Live', 'Audit', 'Traces', 'Events', 'Loop-guard'],
    section: 'Event stream',
    rows: [
      ['Tool call completed', 'query_memory', '184 ms', 'Open'],
      ['Task state changed', 'task_8f32', 'Running → Review', 'Open'],
      ['Approval requested', 'deploy', 'Risk REVIEW', 'Review'],
      ['Memory stored', 'release workflow preference', 'High', 'Open'],
    ],
    detailsTitle: 'Observability',
    details: ['Live stream connected', '184 events today', '2 warnings', '0 blocked loops'],
    api: ['/audit', '/traces', '/events/history', '/loop-guard/stats', 'WS /ws/dashboard'],
    relations: ['/traces/:sessionId', '/approvals/:id', '/tasks/:id'],
  }),
  sessions: page({
    title: 'Sessions',
    navLabel: 'Sessions',
    route: '/sessions',
    subtitle: 'Conversation and model execution history',
    tabs: ['All', 'By model', 'By date', 'Errors'],
    section: 'Recent sessions',
    rows: [
      ['HiveOS UI architecture review', 'MiniMax M2.7', '8.4k tokens', 'Open'],
      ['Gateway retry diagnosis', 'GPT-5.6', '12.1k tokens', 'Open'],
      ['MCP compatibility research', 'MiniMax M2.7', '6.8k tokens', 'Open'],
      ['Memory recovery', 'MiniMax M2.7', '4.2k tokens', 'Open'],
    ],
    detailsTitle: 'Session summary',
    details: ['1,284 indexed', '18 active today', '248k tokens today', 'Error rate 0.8%'],
    api: ['/sessions', '/sessions/stats', '/sessions/search', '/sessions/{id}'],
    relations: ['/chat/:sessionId', '/traces/:sessionId', '/analytics?view=sessions'],
    rowTargets: ['chat', 'chat', 'chat', 'chat'],
  }),
  approvals: page({
    title: 'Approvals',
    navLabel: 'Approvals',
    route: '/approvals',
    subtitle: 'Human decisions for sensitive operations',
    action: 'Review safe',
    tabs: ['Pending', 'Edits log'],
    section: 'Waiting for review',
    rows: [
      ['Restart hiveos-gateway.service', 'REVIEW', 'Requested 8m ago', 'Review'],
      ['Write deployment configuration', 'REVIEW', 'Requested 14m ago', 'Review'],
      ['External notification', 'MANUAL', 'Requested 21m ago', 'Review'],
    ],
    detailsTitle: 'Safety policy',
    details: ['3 pending', 'Oldest 21m', 'Protected files locked', 'Auto-merge disabled'],
    api: ['/approvals', '/approvals/decide', '/approvals/cancel', '/approvals/edits'],
    relations: ['/approval/:id', '/self-improve?tab=pending', '/activity'],
    rowTargets: ['approval-modal', 'approval-modal', 'approval-modal'],
    primaryTarget: 'approval-modal',
    statusLabel: 'Protected',
  }),
  'self-improve': page({
    title: 'Self-improve',
    navLabel: 'Self-improve',
    route: '/self-improve',
    subtitle: 'Controlled improvements with review and rollback',
    action: 'Run tests',
    tabs: ['Verdicts', 'History', 'Pending edits', 'Run tests', 'Learning'],
    section: 'Recent proposals',
    rows: [
      ['Gateway retry backoff', 'PR', 'Tests passed', 'Open'],
      ['Memory reconnect guard', 'AUTO', 'Applied safely', 'Inspect'],
      ['Approval audit metadata', 'REVIEW', 'Waiting', 'Review'],
      ['SOUL.md update', 'PROTECTED', 'Refused', 'Inspect'],
    ],
    detailsTitle: 'Pipeline',
    details: ['Diagnose', 'Propose', 'Test in isolation', 'Open draft PR', 'Human merge'],
    api: ['/self-improve/status', '/self-improve/history', '/self-improve/pending', '/run-tests'],
    relations: ['/approvals', '/tasks', '/logs?src=self', '/release-log'],
  }),
  analytics: page({
    title: 'Analytics',
    navLabel: 'Analytics',
    route: '/analytics',
    subtitle: 'Model usage, cost and reliability',
    tabs: ['Cost', 'Tokens', 'Sessions', 'Skill usage', 'Errors'],
    metrics: [
      ['Spent today', '£4.82', '78% of daily budget'],
      ['Model calls', '162', '248k tokens'],
    ],
    section: 'Cost by model',
    rows: [
      ['MiniMax M2.7', '112 calls', '164k tokens', '£1.64'],
      ['GPT-5.6', '28 calls', '62k tokens', '£2.71'],
      ['Codex', '22 calls', '22k tokens', '£0.47'],
    ],
    detailsTitle: 'Budget',
    details: ['Limit £6.20', 'Remaining £1.38', 'Projected £5.71', 'Within budget'],
    api: ['/telemetry', '/budget/detail', '/budget/forecast', '/audit/error-rate'],
    relations: ['/sessions', '/skills', '/settings?tab=system'],
  }),
  docs: page({
    title: 'Docs',
    navLabel: 'Docs',
    route: '/docs/:filename?',
    subtitle: 'Architecture, operations and safety references',
    section: 'Documentation',
    rows: [
      ['ARCHITECTURE.md', 'System design', 'Updated today', 'Open'],
      ['STATUS.md', 'Capability matrix', 'Updated today', 'Open'],
      ['API.md', 'Gateway contracts', 'Updated today', 'Open'],
      ['SOUL.md', 'Immutable identity', 'Read-only', 'Open'],
    ],
    detailsTitle: 'Document',
    details: ['Rendered Markdown', 'In-pane search', 'Deep-linkable headings', 'Protected files marked'],
    api: ['Build-time markdown bundle', 'GAP: /docs/search (optional)'],
    relations: ['/settings', '/mcp', '/self-improve'],
  }),
  settings: page({
    title: 'Settings',
    navLabel: 'Settings',
    route: '/settings',
    subtitle: 'Personal, account and system configuration',
    tabs: ['Personal', 'Account', 'System'],
    section: 'Quick settings',
    rows: [
      ['Profile and timezone', 'Personal', 'Europe/London', 'Open'],
      ['LLM pool', 'System', '3 models available', 'Open'],
      ['Channels', 'System', '3 connected', 'Open'],
      ['Safety policy', 'System', 'Protected · read-only', 'Open'],
    ],
    detailsTitle: 'Configuration health',
    details: ['Config valid', 'Secrets masked', 'SOUL.md read-only', 'Approval gate protected'],
    api: ['/config/summary', '/config/validate', '/llm/pool', '/model/catalog'],
    relations: ['/channels', '/mcp', '/docs/SOUL.md', '/env'],
  }),
  'agent-detail': page({
    title: 'Agent detail', navLabel: 'Agent detail', route: '/agents/:agentId', subtitle: 'Current work and execution history', action: 'Pause', tabs: ['Overview', 'Tools', 'Performance', 'Logs'], section: 'coder', rows: [['Current task', 'Gateway retry refactor', 'Running', 'Open task'], ['Latest tool', 'apply_patch', 'Success', 'Open trace'], ['Branch', 'gpt-ui-improvements', 'Clean', 'Open PR']], detailsTitle: 'Runtime', details: ['Latency 184 ms', 'Success 98.2%', 'Steps 4 / 7', 'Memory 6 facts'], api: ['/agents/board', 'WS A2A_CALL_*', 'GAP: /agents/{id}'], relations: ['/agents', '/tasks/:id', '/activity?tab=traces'], rowTargets: ['tasks', 'trace-detail', 'release-log'], statusLabel: 'Running',
  }),
  'command-palette': page({
    title: 'Command palette', navLabel: 'Command palette', route: 'Global overlay', subtitle: 'Search routes, sessions and commands', section: 'Search or run a command', rows: [['Go to Memory', 'Navigation', '⌘2', 'Run'], ['Run tests', 'Command', 'Self-improve', 'Run'], ['Open trace ses_8f912a', 'Navigation', 'Activity', 'Open'], ['Consolidate memory', 'Command', 'Requires confirmation', 'Run']], detailsTitle: 'Indexed sources', details: ['17 routes', 'Sessions', 'Pinned skills', 'Pending approvals'], api: ['Client-side index + existing domain APIs'], relations: ['Every route', '/sessions', '/skills', '/approvals'], rowTargets: ['memory', 'self-improve', 'trace-detail', 'memory'], statusLabel: 'Ready',
  }),
  'approval-modal': page({
    title: 'Approval review', navLabel: 'Approval modal', route: '/approvals/:id overlay', subtitle: 'Review a sensitive operation before it runs', action: 'Approve', section: 'Restart gateway service', rows: [['Tool', 'deploy', 'Risk REVIEW', ''], ['Target', 'hiveos-gateway.service', 'Protected operation', ''], ['Reason', 'Apply reviewed gateway retry fix', 'Requested by Hive', '']], detailsTitle: 'Decision', details: ['Approve once', 'Reject with reason', 'Cancel request', 'Audit every outcome'], api: ['/approvals', '/approvals/decide', '/approvals/cancel'], relations: ['/approvals', '/activity', '/self-improve'], statusLabel: 'Review required',
  }),
  'trace-detail': page({
    title: 'Trace detail', navLabel: 'Trace detail', route: '/traces/:sessionId overlay', subtitle: 'End-to-end execution waterfall', section: 'trace_18fd', rows: [['Plan', 'Build UI contract map', '420 ms', 'Open'], ['Tool', 'inspect_api_routes', '184 ms', 'Open'], ['Agent', 'reviewer validation', '1.8 s', 'Open'], ['Memory', 'Store verified contract', '96 ms', 'Open']], detailsTitle: 'Trace summary', details: ['Duration 2.8 s', '8 events', '0 errors', 'Cost £0.03'], api: ['/traces/{sessionId}', '/traces/export/{sessionId}'], relations: ['/activity?tab=traces', '/sessions/:id', '/chat/:id'],
  }),
  'new-task': page({
    title: 'New task', navLabel: 'New task dialog', route: '/tasks overlay', subtitle: 'Create durable work for Hive or a specialist', action: 'Create task', section: 'Task details', rows: [['Title', 'Review HiveOS UI backend gaps', 'Required', ''], ['Owner', 'reviewer', 'Optional', ''], ['Priority', 'High', 'Queued safely', ''], ['Schedule', 'Run now', 'Cron optional', '']], detailsTitle: 'Routing', details: ['Creates durable task', 'Appears in Kanban', 'Agent receives context', 'Events stream to Activity'], api: ['GAP: POST /tasks', 'Existing cron/commitment create APIs'], relations: ['/tasks', '/agents/:id', '/activity'], statusLabel: 'Draft',
  }),
  notifications: page({
    title: 'Notifications', navLabel: 'Notifications', route: 'Global panel', subtitle: 'Items that need operator awareness', section: 'New', rows: [['Approval waiting', 'Deploy production update', '8m ago', 'Review'], ['Test run completed', 'All checks passed', '12m ago', 'Open'], ['Cron failed', 'Nightly memory consolidation', '18m ago', 'Inspect'], ['Webhook received', 'Telegram · Kamil', '22m ago', 'Open']], detailsTitle: 'Delivery rules', details: ['Approvals always on', 'Budget warnings on', 'Test failures on', 'Webhooks compact'], api: ['/approvals', '/budget/warning', '/events/history', 'WS /ws/dashboard'], relations: ['/approvals', '/activity', '/settings?tab=personal'], rowTargets: ['approval-modal', 'self-improve', 'cron', 'channels'], statusLabel: '4 unread',
  }),
  'release-log': page({
    title: 'Release log', navLabel: 'Release log', route: '/release-log concept', subtitle: 'What changed in every development version', action: 'View changelog', tabs: ['Latest', 'All versions'], section: 'v0.8.2 · Deep UI audit', rows: [['Fixed', 'All 29 mockup states are now reachable', '2026-08-22', ''], ['Fixed', 'Tabs, history, overlays and action routing', '2026-08-22', ''], ['Changed', 'Mobile and tablet navigation accessibility', '2026-08-22', ''], ['Previous', 'v0.8.1 · Professional UI concept package', '2026-08-22', '']], detailsTitle: 'Release discipline', details: ['Added', 'Changed', 'Fixed', 'Removed', 'Security'], api: ['Static changelog data', 'Future: /release-notes'], relations: ['/docs/CHANGELOG.md', '/self-improve', 'GitHub pull requests'],
  }),
  cron: page({
    title: 'Automations', navLabel: 'Automations · Cron', route: '/tasks?tab=cron', subtitle: 'Scheduled work with visible cadence and health', action: 'New schedule', tabs: ['Kanban', 'Cron', 'Promises'], defaultTab: 'Cron', tabTargets: { Kanban: 'tasks', Promises: 'commitments' }, section: 'Schedules', rows: [['Nightly memory consolidation', 'Every day at 02:00', 'Healthy', 'Inspect'], ['Morning health brief', 'Weekdays at 08:00', 'Healthy', 'Inspect'], ['Dependency audit', 'Every Friday at 11:00', 'Paused', 'Inspect']], detailsTitle: 'Schedule health', details: ['2 active', '1 paused', 'Last run succeeded', 'Next run in 4h'], api: ['/cron', '/cron/{id}', '/cron/{id}/run'], relations: ['/tasks', '/commitments', '/activity'], statusLabel: 'Scheduled',
  }),
  commitments: page({
    title: 'Commitments', navLabel: 'Commitments', route: '/tasks?tab=promises', subtitle: 'Recurring promises Hive is accountable for', action: 'New commitment', tabs: ['Kanban', 'Cron', 'Promises'], defaultTab: 'Promises', tabTargets: { Kanban: 'tasks', Cron: 'cron' }, section: 'Open commitments', rows: [['Review critical alerts', 'Daily', 'Due today', 'Open'], ['Weekly system review', 'Friday', 'On track', 'Open'], ['Consolidate durable memory', 'After major work', 'In progress', 'Inspect']], detailsTitle: 'Reliability', details: ['7 active', '96% fulfilled', '1 due today', '0 overdue'], api: ['/commitments', '/commitments/{id}/fulfil'], relations: ['/tasks', '/cron', '/activity'], statusLabel: 'On track',
  }),
  'mobile-hub': page({
    title: 'Hub', navLabel: 'Mobile Hub', route: '/ · 390 px', subtitle: 'Mobile system overview', action: 'New task', metrics: [['Gateway', 'Healthy', '14s ago'], ['Active agents', '3', '2 running'], ['Memory', '12.4k', '98.7% healthy'], ['Approvals', '1', 'Waiting 8m']], section: 'Needs attention', rows: [['Deploy production update', 'Approval', '8m ago', 'Review'], ['Memory consolidation retry', 'Task', 'Ready', 'Inspect'], ['Daily model budget', 'Usage', '78%', 'Open']], detailsTitle: 'Active now', details: ['Gateway retry refactor', 'MCP compatibility research', 'Memory consolidation'], api: ['/health/summary', '/tasks/running'], relations: ['/hub', '/tasks', '/activity'], rowTargets: ['approval-modal', 'tasks', 'analytics'], primaryTarget: 'new-task', presentation: 'mobile',
  }),
  'mobile-chat': page({
    title: 'Chat', navLabel: 'Mobile Chat', route: '/chat/:sessionId · 390 px', subtitle: 'Focused mobile conversation', action: 'New chat', tabs: ['Conversation', 'Run details'], section: 'HiveOS UI architecture review', rows: [['Hive', 'I mapped the UI dependencies.', 'Now', ''], ['Tool call', 'inspect_api_routes · 184 ms', 'Success', 'Open trace'], ['Delegation', 'reviewer validating contracts', 'Running', 'View agent']], detailsTitle: 'Run context', details: ['Session ses_8f912a', 'Model MiniMax M2.7', 'Memory 7 facts', 'Skills 3 loaded'], api: ['/chat/stream/iterations', '/sessions'], relations: ['/sessions/:id', '/memory', '/traces/:id'], rowTargets: [null, 'trace-detail', 'agent-detail'], presentation: 'mobile',
  }),
  'mobile-nav': page({
    title: 'Navigation', navLabel: 'Mobile Nav Drawer', route: 'Global drawer · 390 px', subtitle: 'Every HiveOS destination remains reachable', section: 'All destinations', rows: [['Work', 'Chat · Memory · Skills · Files', '4 views', 'Open'], ['Run', 'Agents · Tasks · Channels · MCP · Logs', '5 views', 'Open'], ['Watch', 'Activity · Sessions · Approvals', '3 views', 'Open'], ['Tune', 'Self-improve · Analytics · Docs · Settings', '4 views', 'Open']], detailsTitle: 'Quick access', details: ['Hub', 'Chat', 'Tasks', 'Activity', 'Settings'], api: ['Client-side routes only'], relations: ['/hub', '/chat', '/tasks', '/settings'], presentation: 'mobile', statusLabel: 'All views',
  }),
};

export const defaultScreenId = 'hub';
